<div class="row">
    <div class="col-md-12">
        <div id="container" style="width:100%; height:500px;"></div>
    </div>
</div>

<script>
    $(function() {
        $('#container').highcharts({
            chart: {
                type: 'bar'
            },
            title: {
                text: ''
            },
            xAxis: {
                categories: [<?= $axis ?>]
            },
            series: [{
                name: 'Обновлено задач',
                data: [<?= $series ?>]
            }, ]
        });
    });
</script>